{{- if .Values.frontend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chess-game.fullname" . }}-frontend
  labels:
    {{ include "chess-game.labels" . | nindent 4 }}
    {{ include "chess-game.componentLabels" "frontend" | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{ include "chess-game.selectorLabels" . | nindent 6 }}
      {{ include "chess-game.componentLabels" "frontend" | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{ include "chess-game.selectorLabels" . | nindent 8 }}
        {{ include "chess-game.componentLabels" "frontend" | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "chess-game.serviceAccountName" . }}
      securityContext:
        {{ toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: frontend
        securityContext:
          {{ toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        envFrom:
        - configMapRef:
            name: {{ include "chess-game.fullname" . }}-frontend-config
        livenessProbe:
          {{ toYaml .Values.frontend.livenessProbe | nindent 12 }}
        readinessProbe:
          {{ toYaml .Values.frontend.readinessProbe | nindent 12 }}
        resources:
          {{ toYaml .Values.frontend.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{ toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
